[variables]
UPLOAD_MAX_FILESIZE = "1024M"
POST_MAX_SIZE = "1024M"
MEMORY_LIMIT = "1024M"
MAX_EXECUTION_TIME = "600"

[phases.setup]
cmds = [
  'echo "upload_max_filesize=1024M; post_max_size=1024M; memory_limit=1024M; max_execution_time=600" > /nix/store/*php*/lib/php.ini'
]
